/*
 * generated by Xtext
 */
package org.uqbar.research.languages;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BaseRuntimeModule extends org.uqbar.research.languages.AbstractBaseRuntimeModule {

}
