/*
 * generated by Xtext
 */
package org.uqbar.research.languages.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BaseUiModule extends org.uqbar.research.languages.ui.AbstractBaseUiModule {
	public BaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
