/*
 * generated by Xtext
 */
package org.uqbar.research.languages.validation

import org.uqbar.research.languages.typing.validation.BaseSemanticsValidator

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class BaseValidator extends BaseSemanticsValidator {
	
}
