/*
 * generated by Xtext
 */
package org.uqbar.research.languages.ui.contentassist

import org.uqbar.research.languages.ui.contentassist.AbstractBaseProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BaseProposalProvider extends AbstractBaseProposalProvider {
}
